---
deployment:
  tasks:
    - export DEPLOYPATH=/home/techfpzx/greenwich-upj-sustainability-project.com
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -r app $DEPLOYPATH
    - /bin/cp -r components $DEPLOYPATH
    - /bin/cp -r public $DEPLOYPATH
    - /bin/cp -r utils $DEPLOYPATH
    - /bin/cp next.config.ts $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
    - /bin/cp tsconfig.json $DEPLOYPATH
    - /bin/cp postcss.config.mjs $DEPLOYPATH
    - /bin/cp eslint.config.mjs $DEPLOYPATH
    - /bin/cp server.js $DEPLOYPATH
    - /bin/cp proxy.ts $DEPLOYPATH
    - /bin/mkdir -p $DEPLOYPATH/tmp
    - /bin/touch $DEPLOYPATH/tmp/restart.txt
